services:
  mysql:
    image: 'mysql:latest'
    restart: always
    environment:
      - 'MYSQL_DATABASE=worklingo'
      - 'MYSQL_PASSWORD=Admin123'
      - 'MYSQL_ROOT_PASSWORD=Admin123'
      - 'MYSQL_USER=user'
    ports:
      - '3307:3306'

  adminer:
    image: 'adminer'
    ports:
      - '8086:8080'