spring:
  application:
    name: WorkLingo
  datasource:
    url: jdbc:mysql://localhost:3306/worklingo
    username: user
    password: Admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true




CLOUDINARY_URL: cloudinary://123456789012345:abcdeFGH1234567ijklmnopqrstuvwx@worklingo
EMAIL_USERNAME: abcde@gmail.com
EMAIL_PASSWORD: 123456

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  port: 8080
